<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>11ff28e8-85ae-44c6-a5c0-58b0c59a4020</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="images\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\profilePic.jpg" />
  </ItemGroup>

</Project>
